convert sprsht_toast_ahk.png -transparent "#ffffff" png32:sprsht_toast_ahk.png
convert sprsht_toast_ahp.png -transparent "#ffffff" png32:sprsht_toast_ahp.png
convert sprsht_toast_air_guard.png -transparent "#ffffff" png32:sprsht_toast_air_guard.png
convert sprsht_toast_air_guard_stun.png -transparent "#ffffff" png32:sprsht_toast_air_guard_stun.png
convert sprsht_toast_alk.png -transparent "#ffffff" png32:sprsht_toast_alk.png
convert sprsht_toast_alp.png -transparent "#ffffff" png32:sprsht_toast_alp.png
convert sprsht_toast_ascending.png -transparent "#ffffff" png32:sprsht_toast_ascending.png
convert sprsht_toast_descending.png -transparent "#ffffff" png32:sprsht_toast_descending.png
convert sprsht_toast_dhk.png -transparent "#ffffff" png32:sprsht_toast_dhk.png
convert sprsht_toast_dhp.png -transparent "#ffffff" png32:sprsht_toast_dhp.png
convert sprsht_toast_dlk.png -transparent "#ffffff" png32:sprsht_toast_dlk.png
convert sprsht_toast_dlp.png -transparent "#ffffff" png32:sprsht_toast_dlp.png
convert sprsht_toast_duck_guard.png -transparent "#ffffff" png32:sprsht_toast_duck_guard.png
convert sprsht_toast_duck_guard_stun.png -transparent "#ffffff" png32:sprsht_toast_duck_guard_stun.png
convert sprsht_toast_duck_hit_stun.png -transparent "#ffffff" png32:sprsht_toast_duck_hit_stun.png
convert sprsht_toast_duck_start.png -transparent "#ffffff" png32:sprsht_toast_duck_start.png
convert sprsht_toast_ducking.png -transparent "#ffffff" png32:sprsht_toast_ducking.png
convert sprsht_toast_ghk.png -transparent "#ffffff" png32:sprsht_toast_ghk.png
convert sprsht_toast_ghp.png -transparent "#ffffff" png32:sprsht_toast_ghp.png
convert sprsht_toast_glk.png -transparent "#ffffff" png32:sprsht_toast_glk.png
convert sprsht_toast_glp.png -transparent "#ffffff" png32:sprsht_toast_glp.png
convert sprsht_toast_grab.png -transparent "#ffffff" png32:sprsht_toast_grab.png
convert sprsht_toast_grab_miss.png -transparent "#ffffff" png32:sprsht_toast_grab_miss.png
convert sprsht_toast_grab_start.png -transparent "#ffffff" png32:sprsht_toast_grab_start.png
convert sprsht_toast_grabbed.png -transparent "#ffffff" png32:sprsht_toast_grabbed.png
convert sprsht_toast_guard.png -transparent "#ffffff" png32:sprsht_toast_guard.png
convert sprsht_toast_guard_stun.png -transparent "#ffffff" png32:sprsht_toast_guard_stun.png
convert sprsht_toast_hit_stun.png -transparent "#ffffff" png32:sprsht_toast_hit_stun.png
convert sprsht_toast_idle.png -transparent "#ffffff" png32:sprsht_toast_idle.png
convert sprsht_toast_juggle.png -transparent "#ffffff" png32:sprsht_toast_juggle.png
convert sprsht_toast_jump_start.png -transparent "#ffffff" png32:sprsht_toast_jump_start.png
convert sprsht_toast_knockdown.png -transparent "#ffffff" png32:sprsht_toast_knockdown.png
convert sprsht_toast_landing.png -transparent "#ffffff" png32:sprsht_toast_landing.png
convert sprsht_toast_recovery.png -transparent "#ffffff" png32:sprsht_toast_recovery.png
convert sprsht_toast_walk.png -transparent "#ffffff" png32:sprsht_toast_walk.png
